### ISSUE TITLE
NetworkWatcher: Module not found: Error: Can't resolve '_http_agent'

### ISSUE THREAD

**Issue by charlesSeek** [TrackJs/TrackJS-Node#16]
I want to use trackjs-node in our ssr react app server side code and it throws errors. 
I found the same error info in the previous closed issue. But there is no solution and just suggest to use browser package.

versions:
```
"trackjs-node": "1.0.1",
"node": 16.16.0,
"react": 18.2.0
```
errors:
```
ERROR in ../../node_modules/.pnpm/trackjs-node@1.0.1/node_modules/trackjs-node/dist/watchers/NetworkWatcher.js 7:16-38
Module not found: Error: Can't resolve '_http_agent' in '/Users/ccui/Dev/wpt-cms-unification/node_modules/.pnpm/trackjs-node@1.0.1/node_modules/trackjs-node/dist/watchers'
```

**Comment by toddhgardner** [comment]
Hi @shuchengc. In previous cases, they were referencing trackjs-node in an isomorphic way where it would get loaded on both the server and the client. In their case, they only needed to run the browser agent, even on the SSR app.

When the Node client is run in a dom-like environment, this error will be thrown because the node network layer does not exist. 

Have a look at [our docs for using the agent in isomorphic environments](https://docs.trackjs.com/node-agent/installation/#isomorphism) and let me know. Otherwise I could use some context to try and recreate the problem.

Thanks!
